# Site settings
author: Victoria Meng
title: I Read So You Don't Have To
header-img: img/home-bg.png
email: nights1ststar@protonmail.com
copyright_name: Victoria Meng
description: > # this means to ignore newlines until "baseurl:"
  Geek girl blogs about her projects and code books she's read
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VictoriaMeng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
