# Site settings
title: First Steps
header-img: img/home-bg.png
email: nights1ststar@protonmail.com
copyright_name: VictoriaMeng
description: > # this means to ignore newlines until "baseurl:"
  Blogging about my journey through Flatiron's Online Web Developer Prog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VictoriaMeng
learn_profile: VictoriaMeng
email_username: nights1ststar@protonmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
